name: Snapshot based E2E OIDC tests workflow

on: [ push, pull_request ]

env:
  OPENSEARCH_VERSION: '3.0.0'
  KEYCLOAK_VERSION: '21.0.1'
  TEST_KEYCLOAK_CLIENT_SECRET: 'oacHfNaXyy81r2uHq1A9RY4ASryre4rZ'
  CI: 1
  # avoid warnings like "tput: No value for $TERM and no -T specified"
  TERM: xterm
  PLUGIN_NAME: opensearch-security
  # This is the SHA256 checksum of the known good kc.sh script for Keycloak version 21.0.1.
  KNOWN_CHECKSUM_OF_KEYCLOAK_SCRIPT: 'f825ea1a9ffa5ad91673737c06857ababbb69b6b8f09e0c637b4c998517f9608'
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: myStrongPassword123!
  
jobs:
  tests:
    name: Run Cypress E2E OIDC tests
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      
      # Add OpenID Configuration
      - name: Creating OpenID Configuration for Linux
        if: ${{ runner.os == 'Linux'}}
        run: |
          echo "Creating new OpenID configuration"
          cat << 'EOT' > config_openid.yml
          ---
          _meta:
            type: "config"
            config_version: 2
          config:
            dynamic:
              http:
                anonymous_auth_enabled: false
              authc:
                basic_internal_auth_domain:
                  description: "Authenticate via HTTP Basic against internal users database"
                  http_enabled: true
                  transport_enabled: true
                  order: 0
                  http_authenticator:
                    type: basic
                    challenge: false
                  authentication_backend:
                    type: intern
                openid_auth_domain:
                  http_enabled: true
                  transport_enabled: true
                  order: 1
                  http_authenticator:
                    type: openid
                    challenge: false
                    config:
                      subject_key: preferred_username
                      roles_key: roles
                      openid_connect_url: http://localhost:8080/auth/realms/master/.well-known/openid-configuration
                  authentication_backend:
                    type: noop
          EOT
          echo "THIS IS THE SECURITY CONFIG FILE: "
          cat config_openid.yml

      # Configure the Dashboard for OpenID setup
      - name: Create OpenSearch Dashboards Config for OpenID
        if: ${{ runner.os == 'Linux' }}
        run: |
          cat << 'EOT' > opensearch_dashboards_openid.yml
          server.host: "localhost"
          opensearch.hosts: ["https://localhost:9200"]
          opensearch.ssl.verificationMode: none
          opensearch.username: "kibanaserver"
          opensearch.password: "kibanaserver"
          opensearch.requestHeadersWhitelist: [ authorization,securitytenant ]
          opensearch_security.multitenancy.enabled: true
          opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
          opensearch_security.readonly_mode.roles: ["kibana_read_only"]
          opensearch_security.cookie.secure: false
          opensearch_security.openid.connect_url: "http://127.0.0.1:8080/auth/realms/master/.well-known/openid-configuration"
          opensearch_security.openid.client_id: "opensearch"
          opensearch_security.openid.client_secret: "${{ env.TEST_KEYCLOAK_CLIENT_SECRET }}"
          opensearch_security.auth.type: ["openid"]
          opensearch_security.auth.multiple_auth_enabled: true
          opensearch_security.ui.openid.login.buttonname: "OIDC"
          home.disableWelcomeScreen: true
          EOT
          echo 'HERE IS THE DASHBOARD CONFIG FILE: '
          cat opensearch_dashboards_openid.yml

      - name: Run Cypress Tests
        uses: ./.github/actions/run-cypress-tests
        with:
          security_config_file: config_openid.yml
          dashboards_config_file: opensearch_dashboards_openid.yml
          yarn_command: 'yarn cypress:run --browser chrome --headless --spec "test/cypress/e2e/oidc/*.js"'
