name: Integration Tests Windows

on: [push, pull_request]

defaults:
  run:
    working-directory: &workdir 'C:\github\security-dashboards-plugin' ## Use disk C: because D: is out of space

env:
  TEST_BROWSER_HEADLESS: 1
  CI: 1
  PLUGIN_NAME: opensearch-security

jobs:
  tests:
    name: Run integration tests
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    
      - name: create working-directory
        run: set -x; mkdir -p "$workdir"; echo $PWD
        working-directory: 'C:\'
        env: { workdir: *workdir }

      - name: Checkout
        uses: actions/checkout@v3
        with: 
          path: *workdir
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set env
        run: |
          opensearch_version=$(node -p "require('./package.json').opensearchDashboards.version")
          plugin_version=$(node -p "require('./package.json').version")
          echo "OPENSEARCH_VERSION=$opensearch_version" >> $GITHUB_ENV
          echo "PLUGIN_VERSION=$plugin_version" >> $GITHUB_ENV
        shell: bash

      - uses: browser-actions/setup-geckodriver@v0.0.0
      - run: geckodriver --version

      # Browser-action version does not work on Windows
      - name: Set up Firefox browser
        uses: RyanL1997/setup-browser@main
        with:
          browser: firefox
          version: latest

      - name: Download security plugin and create setup scripts
        uses: ./.github/actions/download-plugin
        with:
          opensearch-version: ${{ env.OPENSEARCH_VERSION }}
          plugin-name: ${{ env.PLUGIN_NAME }}
          plugin-version: ${{ env.PLUGIN_VERSION }}

      - name: Run Opensearch with A Single Plugin
        uses: opensearch-project/security/.github/actions/start-opensearch-with-one-plugin@main
        with:
          opensearch-version: ${{ env.OPENSEARCH_VERSION }}
          plugin-name: ${{ env.PLUGIN_NAME }}
          setup-script-name: setup
          admin-password: admin

      - id: install-dashboards
        uses: ./.github/actions/install-dashboards
        with:
          plugin_name: security-dashboards-plugin

      - name: Start Dashboards in background
        run: node scripts/build_opensearch_dashboards_platform_plugins.js
        working-directory: ${{ steps.install-dashboards.outputs.dashboards-directory }}

      - name: Yarn cache clean
        run: yarn cache clean

      - name: Run integration tests
        run: |
          echo "check if opensearch is ready"
          curl -XGET https://localhost:9200 -u 'admin:admin' -k
          node .\test\run_jest_tests.js --config .\test\jest.config.server.js --testPathIgnorePatterns saml_auth.test.ts --testPathIgnorePatterns saml_multiauth.test.ts
        working-directory: ${{ steps.install-dashboards.outputs.plugin-directory }}
